Repository icon-project/intent-contracts, pull requests merged in 2024-10, with the labels that each got.

#3 Feat:evm intents
  Cargo.lock
  contracts/evm/.env.example
  contracts/evm/README.md
  contracts/evm/cache/solidity-files-cache.json
  contracts/evm/contracts/Intents/Encoding.sol
  contracts/evm/contracts/Intents/GeneralizedConnection.sol
  contracts/evm/contracts/Intents/IPermit2.sol
  contracts/evm/contracts/Intents/Intents.sol
  contracts/evm/contracts/Intents/Permit2OrderLib.sol
  contracts/evm/contracts/Intents/Types.sol
  contracts/evm/contracts/adapters/CentralizedConnection.sol
  contracts/evm/contracts/adapters/LayerZeroAdapter.sol
  contracts/evm/contracts/adapters/WormholeAdapter.sol
  contracts/evm/contracts/adapters/interfaces/ILayerZeroAdapter.sol
  contracts/evm/contracts/adapters/interfaces/IWormholeAdapter.sol
  contracts/evm/contracts/mocks/dapp/DAppProxySample.sol
  contracts/evm/contracts/mocks/multi-protocol-dapp/MultiProtocolSampleDapp.sol
  contracts/evm/contracts/xcall/CallService.sol
  contracts/evm/contracts/xcall/CallServiceV1.sol
  contracts/evm/contracts/xcall/interfaces/IConnection.sol
  contracts/evm/contracts/xcall/interfaces/IFeeManage.sol
  contracts/evm/deploy_script.sh
  contracts/evm/forge_build.sh
  contracts/evm/foundry.toml
  contracts/evm/library/utils/LibRLPStruct.sol
  contracts/evm/library/utils/RLPDecodeStruct.sol
  contracts/evm/library/utils/RLPEncodeStruct.sol
  contracts/evm/library/utils/Types.sol
  contracts/evm/library/xcall/interfaces/IBSH.sol
  contracts/evm/library/xcall/interfaces/ICallService.sol
  contracts/evm/library/xcall/interfaces/ICallServiceReceiver.sol
  contracts/evm/library/xcall/interfaces/ICallServiceV1.sol
  contracts/evm/library/xcall/interfaces/IDefaultCallServiceReceiver.sol
  contracts/evm/library/xcall/utils/Integers.sol
  contracts/evm/library/xcall/utils/NetworkAddress.sol
  contracts/evm/remappings.txt
  contracts/evm/script/CallService.s.sol
  contracts/evm/script/XCallOperation.s.sol
  contracts/evm/test/Intents/Encoding.t.sol
  contracts/evm/test/Intents/Intents.t.sol
  contracts/evm/test/adapters/CentralizedConnection.t.sol
  contracts/evm/test/adapters/LayerZeroAdapter.t.sol
  contracts/evm/test/adapters/WormholeAdapter.t.sol
  contracts/evm/test/xcall/CallService.t.sol
  contracts/evm/test/xcall/CallServiceV1.t.sol
  contracts/evm/test_xcall_flow.sh
Labels: documentation, enhancement

#6 ci: cleanup
  .github/workflows/publish_maven.yml
  .github/workflows/uat-deploy-java-contracts.yml
  README.md
Labels: documentation, cicd

#4 fix: Fix encoding for permit2
  contracts/evm/contracts/Intents/Intents.sol
  contracts/evm/contracts/Intents/Permit2OrderLib.sol
  contracts/evm/test/Intents/Encoding.t.sol
  contracts/evm/test/Intents/Intents.t.sol
Labels: enhancement

#7 feat: add setters for evm intents
  contracts/evm/contracts/Intents/Intents.sol
  contracts/evm/remappings.txt
  contracts/evm/test/Intents/Intents.t.sol
Labels: enhancement
